name: Bug report
description: Create a bug report to help us improve
labels:
  - bug
  - bug-report
  - to-triage
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: OpenWrt version
      description: |
        The OpenWrt release or commit hash where this bug occurs (use command below).
        ```. /etc/openwrt_release && echo $DISTRIB_REVISION```
    validations:
      required: true
  - type: dropdown
    id: image_kind
    attributes:
      label: Image kind
      options:
        - FOSS
        - NSS
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the reported behaviour.
